name: Blog Agibank E2E • Cypress + Cucumber

on:
  push:
    branches: [main, develop, pipeline/include-github-workflows-to-ci/cd]
  pull_request:
    branches: [main, develop]

  schedule:
    - cron: "0 3 * * *" # 03:00 UTC, diariamente
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cypress:
    name: Run E2E on ${{ matrix.browser }} (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20]
        browser: [chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Debug list
        run: |
          pwd
          ls -la
          cat package.json || true

      - name: Run Cypress
        run: npx cypress run

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
